version: 3
tasks:
  delete-cycle:
    desc: Delete cycle
    cmds:
      - ./scripts/delete_cycle.sh

  update:
    desc: Update all
    cmds:
      - ./scripts/update_mac.sh
  update:beekeeper-studio:
    desc: Update Beekeeper Studio
    cmds:
      - ./scripts/updates/beekeeper-studio.sh
  secret:edit:
    desc: Edit secrets
    env:
      EDITOR: zed
    cmds:
      - sops edit ./secrets.enc.yaml
  secret:decrypt:
    desc: Decrypt secrets
    cmds:
      - sops --decrypt ./secrets.enc.yaml > ./secrets.yaml
  secret:encrypt:
    desc: Encrypt secrets
    cmds:
      - sops --encrypt ./secrets.yaml > ./secrets.enc.yaml
