version: 3
tasks:
  delete-cycle:
    desc: Delete cycle
    cmds:
      - ./scripts/delete_cycle.sh

  update:
    desc: Update all
    cmds:
      - ./scripts/update_mac.sh
  update:arc:
    desc: Update Arc
    cmds:
      - ./scripts/updates/arc.sh
  update:beekeeper-studio:
    desc: Update Beekeeper Studio
    cmds:
      - ./scripts/updates/beekeeper-studio.sh
  update:aptakube:
    desc: Update Aptakube
    cmds:
      - ./scripts/updates/aptakube.sh
  update:firefox:
    desc: Update Firefox
    cmds:
      - ./scripts/updates/firefox.sh
  update:httpie:
    desc: Update HTTPie
    cmds:
      - ./scripts/updates/httpie.sh
  update:zed:
    desc: Update HTTPie
    cmds:
      - ./scripts/updates/httpie.sh
