// Teammate name pool. Names are NOT globally unique — a name only has to be
// unique among sessions created in the resolution window (5 days), which this
// pool cannot exhaust in normal use. Resolution: most recent session wins.

export const NAME_WINDOW_MS = 5 * 24 * 60 * 60 * 1000;

// prettier-ignore
export const TEAMMATE_NAMES: string[] = [
  'aaron', 'abel', 'abigail', 'ada', 'adam', 'adele', 'adrian', 'adriana', 'agatha', 'agnes',
  'aidan', 'aileen', 'aimee', 'aisha', 'alan', 'alana', 'albert', 'alberta', 'alden', 'alec',
  'alejandro', 'alena', 'alex', 'alexa', 'alexander', 'alexandra', 'alfie', 'alfred', 'alice', 'alicia',
  'alina', 'alisa', 'alison', 'alistair', 'aliyah', 'allan', 'allegra', 'allen', 'allie', 'alma',
  'alonzo', 'alvin', 'alyssa', 'amanda', 'amara', 'amber', 'ambrose', 'amelia', 'amos', 'amy',
  'ana', 'anastasia', 'anders', 'anderson', 'andre', 'andrea', 'andres', 'andrew', 'andy', 'angel',
  'angela', 'angelica', 'angelina', 'angelo', 'angie', 'angus', 'anika', 'anita', 'anna', 'annabel',
  'annalise', 'anne', 'annette', 'annie', 'ansel', 'anthony', 'antoine', 'antonia', 'antonio', 'anya',
  'april', 'archer', 'archie', 'ariana', 'ariel', 'arlene', 'arlo', 'armando', 'arnold', 'arthur',
  'arturo', 'asa', 'ashley', 'ashton', 'aspen', 'astrid', 'atticus', 'aubrey', 'audra', 'audrey',
  'august', 'augusta', 'aurora', 'austin', 'autumn', 'ava', 'avery', 'axel', 'ayla', 'barbara',
  'barnaby', 'barrett', 'barry', 'bart', 'basil', 'bea', 'beatrice', 'beau', 'becky', 'bella',
  'ben', 'benedict', 'benjamin', 'bennett', 'benny', 'bernadette', 'bernard', 'bernice', 'bert', 'bertha',
  'beth', 'bethany', 'betsy', 'betty', 'beverly', 'bianca', 'bill', 'billie', 'billy', 'blaine',
  'blair', 'blake', 'blanche', 'bob', 'bobby', 'bonnie', 'boris', 'boyd', 'brad', 'braden',
  'bradley', 'brady', 'brandon', 'brandy', 'brant', 'braxton', 'brayden', 'brenda', 'brendan', 'brennan',
  'brent', 'brett', 'brian', 'briana', 'bridget', 'brigitte', 'britney', 'brittany', 'brock', 'broderick',
  'brody', 'brooke', 'brooks', 'bruce', 'bruno', 'bryan', 'bryce', 'bryn', 'buck', 'buddy',
  'byron', 'cade', 'caitlin', 'caleb', 'callie', 'callum', 'calvin', 'cameron', 'camila', 'camille',
  'candace', 'cara', 'carl', 'carla', 'carlos', 'carlton', 'carmen', 'carol', 'carole', 'carolina',
  'caroline', 'carolyn', 'carrie', 'carson', 'carter', 'casey', 'cassandra', 'cassidy', 'cassie', 'catalina',
  'catherine', 'cathy', 'cecelia', 'cecil', 'cecilia', 'cedric', 'celeste', 'celia', 'celine', 'cesar',
  'chad', 'chandler', 'chantal', 'charity', 'charlene', 'charles', 'charlie', 'charlotte', 'chase', 'chelsea',
  'cherie', 'cheryl', 'chester', 'cheyenne', 'chloe', 'chris', 'christa', 'christian', 'christina', 'christine',
  'christopher', 'christy', 'cindy', 'claire', 'clara', 'clarence', 'clarissa', 'clark', 'claude', 'claudia',
  'clay', 'clayton', 'clement', 'cleo', 'cliff', 'clifford', 'clint', 'clinton', 'clive', 'clyde',
  'cody', 'cole', 'coleman', 'colette', 'colin', 'colleen', 'collin', 'conan', 'connie', 'connor',
  'conrad', 'constance', 'cooper', 'cora', 'corbin', 'cordelia', 'corey', 'corinne', 'cornelius', 'cosmo',
  'courtney', 'craig', 'cristina', 'crosby', 'cruz', 'crystal', 'curt', 'curtis', 'cynthia', 'cyril',
  'cyrus', 'daisy', 'dakota', 'dale', 'dallas', 'dalton', 'damian', 'damien', 'damon', 'dan',
  'dana', 'dane', 'daniel', 'daniela', 'danielle', 'danny', 'dante', 'daphne', 'darcy', 'daria',
  'darius', 'darlene', 'darnell', 'darrell', 'darren', 'darryl', 'darwin', 'dave', 'david', 'davis',
  'dawn', 'dawson', 'dean', 'deanna', 'debbie', 'deborah', 'debra', 'declan', 'deirdre', 'delaney',
  'delbert', 'delia', 'delilah', 'della', 'delores', 'demetrius', 'denise', 'dennis', 'denny', 'denver',
  'derek', 'derrick', 'desiree', 'desmond', 'devin', 'devon', 'dexter', 'diana', 'diane', 'dianne',
  'diego', 'dillon', 'dimitri', 'dinah', 'dion', 'dixie', 'dmitri', 'dolores', 'dominic', 'dominique',
  'don', 'donald', 'donna', 'donnie', 'donovan', 'dora', 'dorian', 'doris', 'dorothy', 'doug',
  'douglas', 'doyle', 'drake', 'drew', 'duane', 'dudley', 'duke', 'duncan', 'dustin', 'dwayne',
  'dwight', 'dylan', 'earl', 'earnest', 'ed', 'eddie', 'eden', 'edgar', 'edith', 'edmund',
  'edna', 'eduardo', 'edward', 'edwin', 'edwina', 'eileen', 'elaine', 'elbert', 'eleanor', 'elena',
  'eli', 'elias', 'elijah', 'elisa', 'elisabeth', 'elise', 'eliza', 'elizabeth', 'ella', 'ellen',
  'elliot', 'elliott', 'ellis', 'elmer', 'eloise', 'elsa', 'elsie', 'elton', 'elvira', 'elvis',
  'emanuel', 'emerson', 'emil', 'emile', 'emilia', 'emilio', 'emily', 'emma', 'emmanuel', 'emmett',
  'enid', 'enrique', 'enzo', 'eric', 'erica', 'erik', 'erika', 'erin', 'ernest', 'ernesto',
  'ernie', 'errol', 'esme', 'esmeralda', 'esperanza', 'estelle', 'esther', 'ethan', 'ethel', 'eugene',
  'eugenia', 'eunice', 'eva', 'evan', 'evangeline', 'eve', 'evelyn', 'everett', 'ezekiel', 'ezra',
  'fabian', 'faith', 'fannie', 'farrah', 'fatima', 'fay', 'faye', 'felicia', 'felicity', 'felix',
  'ferdinand', 'fernando', 'fidel', 'finley', 'finn', 'fiona', 'fletcher', 'flora', 'florence', 'floyd',
  'flynn', 'forrest', 'foster', 'frances', 'francesca', 'francis', 'francisco', 'frank', 'frankie', 'franklin',
  'fred', 'freda', 'freddie', 'frederick', 'freya', 'frida', 'gabe', 'gabriel', 'gabriela', 'gabrielle',
  'gail', 'gale', 'galen', 'garrett', 'garrison', 'garry', 'garth', 'gary', 'gavin', 'gemma',
  'gene', 'genevieve', 'geoffrey', 'george', 'georgia', 'georgina', 'gerald', 'geraldine', 'gerard', 'gerardo',
  'gertrude', 'gia', 'gideon', 'gilbert', 'gilda', 'giles', 'gillian', 'gina', 'ginger', 'giovanni',
  'giselle', 'gladys', 'glen', 'glenda', 'glenn', 'gloria', 'goldie', 'gordon', 'grace', 'gracie',
  'grady', 'graham', 'grant', 'grayson', 'greg', 'gregor', 'gregory', 'greta', 'gretchen', 'griffin',
  'guadalupe', 'guillermo', 'gus', 'gustavo', 'guy', 'gwen', 'gwendolyn', 'hadley', 'hailey', 'hal',
  'haley', 'hamish', 'hank', 'hanna', 'hannah', 'hans', 'harlan', 'harley', 'harmony', 'harold',
  'harper', 'harriet', 'harrison', 'harry', 'harvey', 'hattie', 'hayden', 'hazel', 'heath', 'heather',
  'hector', 'heidi', 'helen', 'helena', 'henrietta', 'henry', 'herbert', 'herman', 'hilda', 'hillary',
  'holly', 'homer', 'hope', 'horace', 'howard', 'hudson', 'hugh', 'hugo', 'humberto', 'hunter',
  'ian', 'ida', 'ignacio', 'igor', 'iliana', 'imogen', 'india', 'inez', 'ingrid', 'irene',
  'iris', 'irma', 'irving', 'isaac', 'isabel', 'isabella', 'isabelle', 'isaiah', 'isla', 'ismael',
  'israel', 'ivan', 'ivy', 'jack', 'jackie', 'jackson', 'jacob', 'jacqueline', 'jade', 'jaime',
  'jake', 'jamal', 'james', 'jamie', 'jan', 'jana', 'jane', 'janelle', 'janet', 'janice',
  'janine', 'jared', 'jasmine', 'jason', 'jasper', 'javier', 'jay', 'jayden', 'jean', 'jeanette',
  'jeanne', 'jeannie', 'jeff', 'jefferson', 'jeffrey', 'jenna', 'jennifer', 'jenny', 'jeremiah', 'jeremy',
  'jermaine', 'jerome', 'jerry', 'jesse', 'jessica', 'jessie', 'jesus', 'jill', 'jillian', 'jim',
  'jimmy', 'joan', 'joanna', 'joanne', 'joaquin', 'jocelyn', 'jodie', 'jody', 'joe', 'joel',
  'joey', 'johanna', 'john', 'johnny', 'jolene', 'jon', 'jonah', 'jonas', 'jonathan', 'jordan',
  'jorge', 'jose', 'josefina', 'joseph', 'josephine', 'josh', 'joshua', 'josiah', 'josie', 'joy',
  'joyce', 'juan', 'juanita', 'judah', 'judd', 'jude', 'judith', 'judy', 'julia', 'julian',
  'juliana', 'julie', 'juliet', 'juliette', 'julio', 'julius', 'june', 'junior', 'justin', 'justine',
  'kai', 'kaitlyn', 'kaleb', 'kara', 'kareem', 'karen', 'karin', 'karina', 'karl', 'karla',
  'kasey', 'kate', 'katelyn', 'katherine', 'kathleen', 'kathryn', 'kathy', 'katie', 'katrina', 'katy',
  'kay', 'kayla', 'kaylee', 'keanu', 'keaton', 'keegan', 'keith', 'kelly', 'kelsey', 'kelvin',
  'ken', 'kendall', 'kendra', 'kendrick', 'kennedy', 'kenneth', 'kenny', 'kent', 'kenya', 'kerry',
  'kevin', 'kiara', 'kieran', 'kim', 'kimberly', 'kingsley', 'kira', 'kirby', 'kirk', 'kirsten',
  'kit', 'klaus', 'knox', 'kobe', 'kody', 'kris', 'krista', 'kristen', 'kristin', 'kristina',
  'kristine', 'kristopher', 'kristy', 'kurt', 'kyla', 'kyle', 'kylie', 'lacey', 'lachlan', 'lamar',
  'lana', 'lance', 'landon', 'lane', 'lara', 'larry', 'laura', 'laurel', 'lauren', 'laurence',
  'laurie', 'laverne', 'lawrence', 'layla', 'lea', 'leah', 'leander', 'lee', 'leif', 'leila',
  'lena', 'lennox', 'lenny', 'leo', 'leon', 'leona', 'leonard', 'leonardo', 'leonel', 'leonora',
  'leopold', 'leroy', 'lesley', 'leslie', 'lester', 'leticia', 'levi', 'lewis', 'lex', 'lexi',
  'liam', 'liana', 'libby', 'lidia', 'lila', 'lilian', 'liliana', 'lillian', 'lillie', 'lily',
  'lincoln', 'linda', 'lindsay', 'lindsey', 'lionel', 'lisa', 'liv', 'livia', 'liz', 'liza',
  'lizzie', 'lloyd', 'logan', 'lois', 'lola', 'london', 'lonnie', 'lora', 'lorelei', 'lorena',
  'lorenzo', 'loretta', 'lori', 'lorna', 'lorraine', 'lottie', 'lou', 'louie', 'louis', 'louisa',
  'louise', 'lourdes', 'lowell', 'luca', 'lucas', 'lucia', 'lucian', 'luciano', 'lucille', 'lucinda',
  'lucy', 'luella', 'luis', 'luke', 'lula', 'luna', 'lupe', 'luther', 'lydia', 'lyle',
  'lynda', 'lynette', 'lynn', 'lyra', 'mabel', 'mable', 'mack', 'mackenzie', 'macy', 'maddox',
  'madeleine', 'madeline', 'madelyn', 'madison', 'mae', 'maeve', 'magdalena', 'maggie', 'magnus', 'maia',
  'malachi', 'malcolm', 'malia', 'mallory', 'mandy', 'manuel', 'mara', 'marc', 'marcel', 'marcella',
  'marcia', 'marco', 'marcos', 'marcus', 'margaret', 'margarita', 'margie', 'margo', 'margot', 'maria',
  'mariah', 'marian', 'marianne', 'maribel', 'marie', 'marietta', 'marilyn', 'marina', 'mario', 'marion',
  'marisa', 'marisol', 'marissa', 'marjorie', 'mark', 'marlene', 'marlon', 'marsha', 'marshall', 'marta',
  'martha', 'martin', 'martina', 'marty', 'marvin', 'mary', 'mason', 'mathew', 'matilda', 'matt',
  'matthew', 'mattie', 'maude', 'maura', 'maureen', 'maurice', 'mauricio', 'max', 'maxine', 'maxwell',
  'may', 'maya', 'meadow', 'meagan', 'megan', 'meghan', 'melanie', 'melba', 'melinda', 'melissa',
  'melody', 'melvin', 'mercedes', 'meredith', 'merle', 'mervin', 'mia', 'micah', 'michael', 'michaela',
  'michele', 'michelle', 'mickey', 'miguel', 'mike', 'mikhail', 'mila', 'milan', 'mildred', 'miles',
  'milo', 'milton', 'mindy', 'minerva', 'minnie', 'miranda', 'miriam', 'misty', 'mitch', 'mitchell',
  'mohammed', 'moira', 'mollie', 'molly', 'mona', 'monica', 'monique', 'monroe', 'montgomery', 'monty',
  'mordecai', 'morgan', 'morris', 'moses', 'muriel', 'murphy', 'murray', 'myles', 'myra', 'myrtle',
  'nadia', 'nadine', 'nancy', 'naomi', 'natalia', 'natalie', 'natasha', 'nathan', 'nathaniel', 'neal',
  'ned', 'neil', 'nell', 'nellie', 'nelson', 'nero', 'nestor', 'nevaeh', 'neville', 'nicholas',
  'nick', 'nicola', 'nicolas', 'nicole', 'nigel', 'nikki', 'nikolai', 'nils', 'nina', 'noah',
  'noel', 'noelle', 'nolan', 'nora', 'norma', 'norman', 'nova', 'nyla', 'oakley', 'octavia',
  'odessa', 'olga', 'olive', 'oliver', 'olivia', 'ollie', 'omar', 'opal', 'ophelia', 'orion',
  'orlando', 'orville', 'oscar', 'osvaldo', 'otis', 'otto', 'owen', 'pablo', 'paige', 'pam',
  'pamela', 'paola', 'paris', 'parker', 'pascal', 'pat', 'patience', 'patricia', 'patrick', 'patsy',
  'patti', 'paul', 'paula', 'paulette', 'pauline', 'paxton', 'pearl', 'pedro', 'peggy', 'penelope',
  'penny', 'percy', 'perla', 'perry', 'pete', 'peter', 'peyton', 'phil', 'philip', 'phillip',
  'phoebe', 'phoenix', 'phyllis', 'pierce', 'pierre', 'piper', 'polly', 'porter', 'preston', 'primrose',
  'priscilla', 'prudence', 'quentin', 'quincy', 'quinn', 'rachael', 'rachel', 'rae', 'rafael', 'raheem',
  'ralph', 'ramona', 'ramon', 'randall', 'randolph', 'randy', 'raphael', 'raquel', 'raul', 'raven',
  'ray', 'rayden', 'raymond', 'reagan', 'rebecca', 'reed', 'reese', 'regina', 'reginald', 'reid',
  'reilly', 'remi', 'remington', 'remy', 'rena', 'rene', 'renee', 'reuben', 'rex', 'reyna',
  'rhea', 'rhett', 'rhoda', 'rhonda', 'ricardo', 'richard', 'richie', 'rick', 'rickey', 'ricky',
  'rico', 'riley', 'rita', 'river', 'rob', 'robbie', 'robert', 'roberta', 'roberto', 'robin',
  'robyn', 'rocco', 'rochelle', 'rocky', 'rod', 'roderick', 'rodney', 'rodolfo', 'rodrigo', 'roger',
  'roland', 'rolando', 'roman', 'romeo', 'ron', 'ronald', 'ronda', 'ronnie', 'rory', 'rosa',
  'rosalie', 'rosalind', 'rosalinda', 'rosanne', 'rose', 'rosemarie', 'rosemary', 'rosie', 'ross', 'rowan',
  'rowena', 'roxanne', 'roy', 'royce', 'ruben', 'ruby', 'rudolph', 'rudy', 'rufus', 'rupert',
  'russ', 'russell', 'rusty', 'ruth', 'ryan', 'ryder', 'rylee', 'sabrina', 'sadie', 'sage',
  'sally', 'salvador', 'salvatore', 'sam', 'samantha', 'samir', 'sammy', 'samson', 'samuel', 'sandra',
  'sandy', 'santiago', 'saoirse', 'sara', 'sarah', 'sasha', 'saul', 'savannah', 'sawyer', 'scarlett',
  'scott', 'seamus', 'sean', 'sebastian', 'selena', 'selma', 'serena', 'sergio', 'seth', 'shane',
  'shannon', 'shari', 'sharon', 'shaun', 'shawn', 'sheila', 'shelby', 'sheldon', 'shelley', 'sheri',
  'sherman', 'sherry', 'sheryl', 'shirley', 'sidney', 'sienna', 'sierra', 'silas', 'silvia', 'simon',
  'simone', 'skylar', 'sloane', 'sofia', 'solomon', 'sonia', 'sonja', 'sonny', 'sonya', 'sophia',
  'sophie', 'spencer', 'stacey', 'stacy', 'stan', 'stanley', 'stefan', 'stella', 'stephan', 'stephanie',
  'stephen', 'sterling', 'steve', 'steven', 'stewart', 'stuart', 'sue', 'summer', 'susan', 'susanna',
  'susie', 'sutton', 'suzanne', 'sybil', 'sydney', 'sylvia', 'tabitha', 'tamara', 'tammy', 'tanner',
  'tanya', 'tara', 'tasha', 'tatiana', 'taylor', 'ted', 'teddy', 'teresa', 'terrance', 'terrence',
  'terri', 'terry', 'tess', 'tessa', 'thaddeus', 'thea', 'thelma', 'theo', 'theodore', 'theresa',
  'thomas', 'thora', 'tiffany', 'tim', 'timothy', 'tina', 'titus', 'tobias', 'toby', 'todd',
  'tom', 'tommy', 'toni', 'tony', 'tonya', 'tracey', 'tracy', 'travis', 'trent', 'trenton',
  'trevor', 'trey', 'tricia', 'trina', 'trisha', 'tristan', 'troy', 'trudy', 'tucker', 'twyla',
  'tyler', 'tyrone', 'tyson', 'ulysses', 'uma', 'ursula', 'valentina', 'valentino', 'valerie', 'vanessa',
  'vance', 'vaughn', 'velma', 'vera', 'verna', 'vernon', 'veronica', 'vicente', 'vicki', 'vickie',
  'vicky', 'victor', 'victoria', 'vince', 'vincent', 'viola', 'violet', 'virgil', 'virginia', 'vivian',
  'viviana', 'vladimir', 'wade', 'walker', 'wallace', 'walter', 'wanda', 'warren', 'waylon', 'wayne',
  'wendell', 'wendy', 'wesley', 'weston', 'whitney', 'wilbur', 'wilfred', 'wilhelmina', 'will', 'willa',
  'william', 'willie', 'willis', 'willow', 'wilma', 'wilson', 'winifred', 'winston', 'wren', 'wyatt',
  'xander', 'xavier', 'ximena', 'yasmin', 'yolanda', 'yvette', 'yvonne', 'zachariah', 'zachary', 'zack',
  'zane', 'zara', 'zelda', 'zeke', 'zoe', 'zoey', 'zola', 'zora',
];

/** Pick a teammate name: uniform-random among names unused in the window; if the
 *  whole pool is somehow used, fall back to the least-recently-used name. */
export function pickTeammateName(recentlyUsed: Iterable<string>, lastUsedAt?: Map<string, number>): string {
  const used = new Set<string>();
  for (const name of recentlyUsed) used.add(name.toLowerCase());
  const available = TEAMMATE_NAMES.filter(name => !used.has(name));
  if (available.length > 0) return available[Math.floor(Math.random() * available.length)]!;
  let best = TEAMMATE_NAMES[0]!;
  let bestTime = Number.POSITIVE_INFINITY;
  for (const name of TEAMMATE_NAMES) {
    const time = lastUsedAt?.get(name) ?? 0;
    if (time < bestTime) {
      bestTime = time;
      best = name;
    }
  }
  return best;
}
