api-keys:
  - ENC[AES256_GCM,data:pv8ngFM5I+cXBcgR2CEhEKePVTHYOrMGvpqfIH+WyIZRCJDs,iv:9ONTZHaVsVbJgOoxpkdQvPd5uqjAvdaXlQmDIuSdIUw=,tag:MB3jOqA34eYJDYGB1552lA==,type:str]
  - ENC[AES256_GCM,data:H6tAVxhdP+QutTb5nhYVPWHUw+/u0jS2+ou3kpi8gzRWTHtX,iv:5+y4y24hfvIWdcQsB8ldPjF7X6/2/nFR9xkasge83T8=,tag:IZEctqgsansCJ3rBmLToxg==,type:str]
claude-api-key:
  - api-key: ENC[AES256_GCM,data:jRhKS2zouNGIK6X8fMkDvtJBTKoWB3stJqqG8grtDAVu8hi2tjDGMG9wSl6e/wTy8A==,iv:nJmWbahMhwaamsAiPGcR44qBRzBabplTYdz2vwjCyEQ=,tag:MYts76Ltr65pdW0gHlGgAg==,type:str]
    base-url: ENC[AES256_GCM,data:6egUGTdUSeQbEbz43uY9Sp8OBy8IoS7slCgCtwLP,iv:eYdJKItF9X3XcvroC/mMK09ma0bM8ywgRVbt/qitZs4=,tag:mNz6cdsJcNBwjHcXBxXzeg==,type:str]
    models:
      - name: ENC[AES256_GCM,data:GQVIseU=,iv:Sw8X5MB6Vhr/OpB/3VAzAv1sXI7CLrc0dE3/PyF4y/A=,tag:45/fnJs9Q9tZ/J/q7/7CZg==,type:str]
      - name: ENC[AES256_GCM,data:WDmD+PO5Fg==,iv:gHjHEf0SCodCxT9k9wJmVstuoPhoYQQi+/oJk1V/RzI=,tag:ESsPvm2NfeIa1oQZdOheQg==,type:str]
      - name: ENC[AES256_GCM,data:/NTBFJNwLw==,iv:hgN10ZwzkYvInNZfkHuC/ruRiwJUDKbPqGZ7asTfJAU=,tag:qiRaOXYyDw4OwHSoA3B1Iw==,type:str]
      - name: ENC[AES256_GCM,data:W8q6AuApzg==,iv:ZNjBLpREQqYR1Mfbbp5U/NxgUGROuc9YDSqk5t+j1bM=,tag:v3tEhtydtKVm1OmKyqC2zA==,type:str]
      - name: ENC[AES256_GCM,data:v9CHW4PA+rohJK8=,iv:Re0a30SRRUtMH7GRJFQkI+zJu4CdgKMplIZDQkZ4/fw=,tag:DQlolywlGTLWz79OJXcifQ==,type:str]
      - name: ENC[AES256_GCM,data:/JuuB+svl3rsR3Q=,iv:k4rPnLhQ0iJlY7EDlbMQPnGDrsq8Vq1u8jkQkcOOfIk=,tag:3ytYKNtsHtX73VTyAZMvog==,type:str]
        alias: ''
      - name: ENC[AES256_GCM,data:QZXGMdR2nQ==,iv:WKaq8Pl3NVOJ3b2lMf39hc9g5BD0riBzUUNWOWrkKWs=,tag:UHQdit5ZeHwErdZNXWaDAQ==,type:str]
        alias: ''
      - name: ENC[AES256_GCM,data:i1Xxora7Sw==,iv:VGbT5xSCoF2NdHA7B7kPusdIQfHWON94CbJFEwlRvwk=,tag:JYac0QClnyWcp3Gf/Dppzg==,type:str]
        alias: ENC[AES256_GCM,data:u6gIP8R+mqU=,iv:HWuU6ZAYMCHFniMM/YhGZYRBKXYivztfLknqhYN+t6c=,tag:SK8scRYL9H+UfnRAaTVEVg==,type:str]
  - api-key: ENC[AES256_GCM,data:QoLQCR+394/SNRjYtwZ2olAXDDTL3Dj2LXSHsNtgpe+sX7XWxVyjz26+ROUSI0ffZA==,iv:/vttUYjm/edLCpdEyQRvpoMgcXAI+AXXPs2GhBgXXcs=,tag:9pcjsgPmMfOMHO9zq/uSNw==,type:str]
    base-url: ENC[AES256_GCM,data:SZir29y13bYRZVgmvsXTqes+J44Cz1e8RhIDePzD,iv:IHSTu3/bnfpVjbq/eajrWH7ERGqWE3e/EZk+KOYheKk=,tag:Av+4uenDAHkFiBIIRsNjiA==,type:str]
    models:
      - name: ENC[AES256_GCM,data:Uxtaw3w=,iv:HTvyBQ9IHRnJzw3AjwVzJBtJBZG886iQEXBZy16hph8=,tag:5CXblEQ7kO5moVdHXMqG3A==,type:str]
      - name: ENC[AES256_GCM,data:IVA7dZPUMg==,iv:OCqZ5Vjx7x2YZip/dyP8NciLHMY3997LsW5A8k8bcwM=,tag:7XnJ0I26G6SaRHhrZw233g==,type:str]
      - name: ENC[AES256_GCM,data:KWJXgPtZNQ==,iv:VRqtD/mpQdDuOksiTU/SuXndmQzz6hvIC4CTkIs7VWE=,tag:EkJKIFVe8KgIQyzLE54J2Q==,type:str]
      - name: ENC[AES256_GCM,data:tFbFi4ynfw==,iv:h5QGQxfPXXKaPcDkGpaamJIBBo5yFdHD/eR4MvBi3x0=,tag:YiSt1QC1uT+gLqNYfYQCSw==,type:str]
      - name: ENC[AES256_GCM,data:lI4PyOzlyfNHhSw=,iv:p1ApxgHrXTmKV2Y5QFPwyjA45broVOaInu2D3nIiwmM=,tag:beG2wh5g4V/br9E50bsDfA==,type:str]
      - name: ENC[AES256_GCM,data:1fWDIonF/zyygds=,iv:TbMomxOQ19c5/SeOw5jIhEq54d8ApEb1+WawVMIsbm4=,tag:5cF6lprsjuQVZu47iGGFug==,type:str]
        alias: ''
      - name: ENC[AES256_GCM,data:sZNteDkOiw==,iv:zl1s6I0v7q0xdjFRjy6N6MwTZDb/MCRRMoRhMqnM5TA=,tag:A78I4/bFtlRVq0lf32wgxg==,type:str]
        alias: ''
      - name: ENC[AES256_GCM,data:aQsJx1gJKQ==,iv:MCBt4BlkYlQleHseIdDvhucE7X/89S67I8vc3Czui40=,tag:qT6BfufiA+Z1waqzp3Bp+g==,type:str]
        alias: ENC[AES256_GCM,data:nTIhHoZcoG4=,iv:Cd0jCNajgvfHXvm476g1V2uZs/ESiV0lufJ5dG/IcsY=,tag:c/WXVkIQdeHZvfU4A/+epA==,type:str]
    proxy-url: ''
  - api-key: ENC[AES256_GCM,data:UJeoDEBpqb2A17g/pItleii1pxJ4hXZNpKHHLOTdcCM6xXt3tSILvN1SJqI/N0lWXdwcOlHJ2tPPb+PTzX+nK/lFZyzjapLvkmoMQR+sY+zW+HVxO0R9aLAwXChwdl9Z/VOGUPLO+YmOgJlchVeKKDayF/ktKR3NVnXzang=,iv:L/EcMFs3t3xIeuD7qDW33Cp7j18TwyatZ0w06afAt8U=,tag:8vIQU0KeXjEIbz34iJFkRA==,type:str]
    base-url: ENC[AES256_GCM,data:w/NLS/CyGtcJfuVq8wngQn0a9nfQOeaF3qfuPv6aszo=,iv:h3exTdABzLMHvMqDjCirHoHVxXo39pxOirbXD/VKz7o=,tag:NCaQHacgI2YzI4zT5PpXbw==,type:str]
    proxy-url: ''
    models:
      - name: ENC[AES256_GCM,data:6r0yDEvyYJaOU6J8,iv:NBAroto7iYEuGA49YEhtIYiysKXkBr2XMcXCStdoSIM=,tag:qUiLRYzNuPlBd74TWGteHQ==,type:str]
        alias: ENC[AES256_GCM,data:ZMbIDQ1p1il9AbKk,iv:Jn3sb6WS8VMBP5m0QIjSHWyuRVrfZpbPjLAvpTt42LI=,tag:pYMEfYILlm3ifElerUZ6tQ==,type:str]
      - name: ENC[AES256_GCM,data:ikRCvUBtLvYkTaX5,iv:pjM5crYXEcoViOecIjlhzxYxIVPTlYkg75JNAGOBU9o=,tag:30BFxuMjC/4bkCOc/bqq/A==,type:str]
        alias: ENC[AES256_GCM,data:ozF+jNGDiIMEx/sy,iv:/qLqjg711RBVw/shQLacd6Oxzt7RLjqLQ2BFOOQADHM=,tag:RDYmg5HIF/wQ4nTgKmQYaA==,type:str]
      - name: ENC[AES256_GCM,data:htmXR4hK/ljHWzN8,iv:FnC0rEkiiOfeR/GJCjafSVC7iHU16bWJ7anc4dxm/fY=,tag:wnioOTrVaeMN1jQK6ChN1g==,type:str]
        alias: ENC[AES256_GCM,data:vPhhLMawO6ZsmOrK,iv:46FaMNrXFKF5CN3EsyWRa3Tmz39fhBzMH2PfIopv6cc=,tag:IMrxCsxgbQoIK+cp/+7NvQ==,type:str]
      - name: ENC[AES256_GCM,data:KIpzeuA+2gdgrw==,iv:zwokmZnU6t3/ItL3DBvGw63MNDtF2rIrkmU79wcTrII=,tag:7o2UvTR6+Q98BHek2dXLTw==,type:str]
        alias: ENC[AES256_GCM,data:Wifwo7ONqEYqzg==,iv:4wFHhLtrk6tIyO1uMLGZXgEdPm/qP/+9id2J04recSM=,tag:twpc29uGUfPKo57d0GMToQ==,type:str]
      - name: ENC[AES256_GCM,data:P/qQifnCAiPCKw==,iv:j4ouqVrb+AhhJ/Qd5vNkLn6ikoEICE9PlMamAFkbmTk=,tag:2Vft3vlG21u17HWRyEQ1JQ==,type:str]
        alias: ENC[AES256_GCM,data:Yw0S0INzNI9qow==,iv:HVcx+BnDruiiBin0ZNabHvOgdYKYONLW2ckn0q6q/JE=,tag:h8rQfbvYoIRecxurfUgFZQ==,type:str]
  - api-key: ENC[AES256_GCM,data:Aqx8kCXRXNvux81Mfp1rjju54NBowx0t8711WOxm8LWFoQQ=,iv:wdCQtfp0EOGmCxp47+UuzCQ6ybN6jLgG0CgKEG1WFac=,tag:74dVWPFSyg/g0ILepQxrRw==,type:str]
    base-url: ENC[AES256_GCM,data:ezvAD5vZopPM6Q9arAzdFt0cdkpIyk9EvYsV6i4u+GzRZw==,iv:5bgVRac+wDlCy2IkFlInUOSZw+U7Ji18Dr4lHsl7vn8=,tag:aEjQ+4cHnvXbhYPG03QbcA==,type:str]
    proxy-url: ''
    models:
      - name: ENC[AES256_GCM,data:fAVGut+/Qh4fV0VFpHxJ,iv:iYwNENTUEn+eHfBwn0gYk9FLkDiRTBqHwwCLWhHsH34=,tag:u227EubuaWHmoC7rDn7fnA==,type:str]
        alias: ''
      - name: ENC[AES256_GCM,data:OPe7PWmkuBJ6CUZQld7zF6w=,iv:Q8Pt3fMID+wfQUSz3hJ6WY8vbjsYP+8amvk3XIQ8v8Q=,tag:BlZkQxR3FjQkV4dtSdsmZw==,type:str]
        alias: ''
openai-compatibility:
  - name: ENC[AES256_GCM,data:cEJMN1yokERv+XNhUAw=,iv:5sOpG/58QiLW9iUfcEUG67lRzghmteH3hNH9GLXEbaI=,tag:gN3vf+N++UDgERmTrOegkA==,type:str]
    base-url: ENC[AES256_GCM,data:tu4T9NsZ+x48jItOPB5x5dwXYjyviXRBLGc=,iv:0+9jabD5EFF3v7qQE/KUJbDT7y5KCqZNpIxlUTRI0YU=,tag:WC15A4t7l8wvjSPEpiREmA==,type:str]
    api-key-entries:
      - api-key: ENC[AES256_GCM,data:I82+4b4HEuegtHSWdQRKLhSo6O+HgC+G0AMDlMOW+CNAy74FpdkJVj7r+3X6chK2y2zDqg==,iv:FiqbCdntcGnLurYw4ltay99rsBdBMdVCkwks6lOVOY0=,tag:GbgntdAjFNx9WdJAR5aJWA==,type:str]
    models:
      - name: ENC[AES256_GCM,data:SwejTCcGUP+UAL+AGpq+rTBqzAQBwpaM9ZwPJHqa,iv:iEpkbhn9FsdEGPnkJXL0UDcyif53giXEWP1BE8MZsdM=,tag:vQrqvUDrafjWrKurCcIHAw==,type:str]
      - name: ENC[AES256_GCM,data:vActwn/EEZe1aYI=,iv:Ovd5lRIjyQzLITjzggj5dnGCMt9qTaNDzDBs0VxD1LE=,tag:AxD3CsWrJU9HGhj/DtMqdw==,type:str]
      - name: ENC[AES256_GCM,data:DMfuIPjoPn//balv,iv:GucnoNiqb4/mvfsXTmL09W+pLSk/TBretbwzn3curFI=,tag:bcdOYiBH24yCeCcntasR1A==,type:str]
      - name: ENC[AES256_GCM,data:9JlGHy8IYz+xnrg=,iv:t2JrPRXjJQvGdQ6i6MkkDGpIqK5IqXlvFiN36a87ax8=,tag:UAJ2q/NC+DfeQ9MT2DyEuA==,type:str]
  - name: ENC[AES256_GCM,data:xP/fpfuMPls=,iv:vxt4VeDk4UvYq+hf/HUWpDKzUo62B0TwBwOBdh5oRAw=,tag:Obag6P0S+yCS5M7lS4LY8A==,type:str]
    base-url: ENC[AES256_GCM,data:RluuPa7Sbddtxpo2GJLNoHsQqCeXzaebKtG75A0BmqyoSI7jgg==,iv:bUgDJYYMR07CW31sKtN5JsIiSyovTpaNyrOafNFUFUg=,tag:BQjQ0nemirIgCmva8nNC9A==,type:str]
    api-key-entries:
      - api-key: ENC[AES256_GCM,data:BUMmbFQbpn8Oiv64rKgies6f0qM3P0guDC/mP+qlMCPourNJsbITjQqZMuzZtSNkIg==,iv:90tLw9rCgczOegrIS7t7QDeK5NH0G+cEyctHyQx6wGk=,tag:ldPi2/Hh50mCg5Z0Jbse3w==,type:str]
    models:
      - name: ENC[AES256_GCM,data:vGqc9GweTvxS23Yw3Q==,iv:DIiTF2d1CRkvdLWWL+29HR+cwcUo8bkXcZRWe56iI6M=,tag:f9vgrLxLfUdJ8iUUnCPpWQ==,type:str]
        alias: ''
      - name: ENC[AES256_GCM,data:/uINf4M3gAwXTcZN8RHQG/Z93gRfrQ==,iv:K2HSFOoZHNWEBfDv0rcMOnAJNzQn7Hn3sxCmy/gskLQ=,tag:N628f1w7+fSOGsQ1esSQTQ==,type:str]
        alias: ''
      - name: ENC[AES256_GCM,data:+z7iCsfgyyWivzWPI41h,iv:5IGtBf4fWz6AeWvZgydP9mwi+B50/f9F3k/hyVNWphU=,tag://TXnvJPaxG6/TNSCatRvQ==,type:str]
        alias: ''
      - name: ENC[AES256_GCM,data:kjHgkOrMC1diGNcrQU7a,iv:idM+ScAZSbewCb/1M98oa1rdgxOHNJytIIt+jCsSc58=,tag:z2JndEe6OHpW+SzO9ePWRA==,type:str]
        alias: ''
  - name: ENC[AES256_GCM,data:um+mDSIQzoep,iv:KdqK70G9DSF+SQSMRAkRTLSqKHgs17qbKVb69OfVsPA=,tag:9NCpNLsCmJbqwbNSgUWhew==,type:str]
    base-url: ENC[AES256_GCM,data:zbJYJA1Ehj+Q6AfDSU0wiOjMNNUnkkgcTmpofl7oMM2+p3k2Og==,iv:ge/M9jNCGy24JsgjuD/9gzLcHoLc04LFhJfq0Neje9Q=,tag:vDhHdqmRX9ue+fc3Z0SKvQ==,type:str]
    api-key-entries:
      - api-key: ENC[AES256_GCM,data:euS22IJlwYSjXgkC+mQ+yxMj+nURkYqLew==,iv:e4HPV5J10uUPs+5NJi4LzKAqZVdo4UeRjpMtyVj1ltQ=,tag:Bd7tFv6CTr1HeInlxYiDXg==,type:str]
    models:
      - name: ENC[AES256_GCM,data:g21C8siztUi3OyHI5KTY8Lv6WSLN/fezM6bOIsACaHb9TP185/P9Nug1,iv:6CCUBFo/e/hSRcbrMi0MHPkNBUHTZN/YoY54e5y27gs=,tag:6foQcEjWNhaBzNpoERbxWg==,type:str]
        alias: ''
      - name: ENC[AES256_GCM,data:4oqQUp6NvmNTRdhAu+coyNu8AnAMoWPBu9+hv3WWgaWmQueIEvo=,iv:P1UQ4Zxu9e+2mxaJPw9cKeanzzVSOeiC29qY+h1dKv0=,tag:VkCBt1n5UDBaBolLESEPhA==,type:str]
        alias: ''
      - name: ENC[AES256_GCM,data:Zn/7bzjhE2s4GXTzHMZJnk2qgkd+V5SMjIAbLtSD/6clOA4=,iv:Re3eVUpsk05iEqcg2ceYBQMFVKeS1j3IctsnpUTa0J8=,tag:7/Ebw2gB4IZWGazLw4N0mQ==,type:str]
        alias: ''
      - name: ENC[AES256_GCM,data:V4ZtULLMcBdgNBDCjP6/aaTFil80rskmjNJqx55IugrkEdtbCcI=,iv:yXnyLi+Q9LTImdpyvTPF3DerjUxI9B87sjYg7PyKqAM=,tag:zWA1S0vYWoOf8+nTf7Vd+w==,type:str]
        alias: ''
      - name: ENC[AES256_GCM,data:BBdtT4V8GYq5UG+2b32oAmEEmfcA+da2g4eIUomYmUyzC+Qy+o4=,iv:0y0yVxsyfFAWkuZHWewckpyNIi0BO6SeiBMmidp04S8=,tag:vUV0wCSfc0JMW8S2y/NFhA==,type:str]
        alias: ''
  - name: ENC[AES256_GCM,data:ETncWKC9siRG,iv:un5tVKVrUSndGlVRiyUmxxDFJrAE7FJtldDkspY/LEg=,tag:n+9yZOL94SncEQXHdD+uvg==,type:str]
    base-url: ENC[AES256_GCM,data:19EVSREFhU/BOFky9/DWAAQvWj8N77a3weRN3A==,iv:Bz33ohLXUU9kARG3vcm5MC0v7SS/Pwz1+51RrA20yPU=,tag:LIdLKKGTF8ln3YTYACQm8g==,type:str]
    api-key-entries:
      - api-key: ENC[AES256_GCM,data:mbZOE50KGHqHv3WiWb+H2TXDPnNaVKkbdjP6znLbSMxoch/k,iv:4HUwV63YphqrPiZM5Fg/bH3oN/xVdJUhz+i7HBoQjaI=,tag:ZpUeldVOG1GQ5bQ22UAJIg==,type:str]
    models:
      - name: ENC[AES256_GCM,data:Ap0ne76wRTgfE2CP,iv:XmJSNc3aMC3hMBNWi5IFJU+qlWaYCBb/1cbDRj7KwKw=,tag:HMHDqF1n1CQ3g87OoIZcZA==,type:str]
        alias: ENC[AES256_GCM,data:JDvUow==,iv:tGxCrQFYcYWGNEYLdguwYgQOXd6sGmDxkXhvxooswOc=,tag:uWAQUrTbVt72yFjH1ml0/Q==,type:str]
remote-management:
  secret-key: ENC[AES256_GCM,data:NSl5CuSREWsrjVHY1RvVwNaWd1tzCxDJ1ZC6f26hUTJB2ZjnOduUGDjMImHsYQ7NxWbYR3BLDCkxDdPh,iv:qf6xNUF/sVQ7pLiIsc8mqjE6x75s2D6G3as8Ct95sxs=,tag:f0plZDga/TW0uTOOOAdDrw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkOGJrZ1UzVDl4WDd1UzZL
        RjgyTXJVdVZPekdFOEY5MlZDM1Mxd09JRmdVClFhRS9Odm05M0s2RXNIQ3Rkd29r
        ZkxVT3R4ZCtXeHdmRk9XZTdBSTlJOFUKLS0tIEhsZXd3dXY0U1lWOTF2ZEpRQmxJ
        VDJEWXhlL2haWStuaFlmUDV4eEpMR00KE7hZCTYyQkDWok2TzWRJC1SUAyI7p8QA
        8jN+w9TJLjJVrJkImP5IvhYQsSTZlWY4eq0FiEXn1szd2AwuzOKEXw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1g6xd3uthuas4aqlwwg74zp4w5jw4jwcju84y9qmqq267aqzf2f7qdatx4w
  lastmodified: '2026-06-25T17:55:06Z'
  mac: ENC[AES256_GCM,data:cO6VD+MC7RpM0Jqz66MPuU4qWX6YEVu4aTwNooMfWWz41wolEnRrkrrOcQ8E1M40r3RjcS6d9lCyuUFTY8eeBmjggZZOgGRihG10CMKJ6VHKnK44oPkBIvKjOGLaKIgpV6r9jsgxtQ58UjPfT4B86sY9KP080Gg93kGYkgxw/2c=,iv:mTdExqN77oHRpv+iX0KgRfKUP2VsjdcZsdKHvYifDao=,tag:B6aiiAt2pvXbsIY1Smm60w==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
