name: CI-CD

on:
  push:

jobs:
  precommit:
    name: Pre-commit Check
    runs-on:
      - nscloud-ubuntu-22.04-amd64-4x8-with-cache
      - nscloud-cache-size-50gb
      - nscloud-cache-tag-home-manager-nix-store-cache
    steps:
      # Setup
      - uses: AtomiCloud/actions.setup-nix@v2
      # pre commit
      - name: Run pre-commit
        run: nix develop .#ci -c ./scripts/ci/pre-commit.sh
